using System;

namespace WindowsFormsApp
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.ButtonQ = new System.Windows.Forms.Button();
            this.ButtonW = new System.Windows.Forms.Button();
            this.ButtonF = new System.Windows.Forms.Button();
            this.ButtonD = new System.Windows.Forms.Button();
            this.ButtonS = new System.Windows.Forms.Button();
            this.ButtonA = new System.Windows.Forms.Button();
            this.ButtonP = new System.Windows.Forms.Button();
            this.ButtonO = new System.Windows.Forms.Button();
            this.ButtonI = new System.Windows.Forms.Button();
            this.ButtonU = new System.Windows.Forms.Button();
            this.ButtonY = new System.Windows.Forms.Button();
            this.ButtonT = new System.Windows.Forms.Button();
            this.ButtonR = new System.Windows.Forms.Button();
            this.ButtonE = new System.Windows.Forms.Button();
            this.ButtonL = new System.Windows.Forms.Button();
            this.ButtonK = new System.Windows.Forms.Button();
            this.ButtonJ = new System.Windows.Forms.Button();
            this.ButtonH = new System.Windows.Forms.Button();
            this.ButtonG = new System.Windows.Forms.Button();
            this.ButtonM = new System.Windows.Forms.Button();
            this.ButtonN = new System.Windows.Forms.Button();
            this.ButtonB = new System.Windows.Forms.Button();
            this.ButtonV = new System.Windows.Forms.Button();
            this.ButtonC = new System.Windows.Forms.Button();
            this.ButtonX = new System.Windows.Forms.Button();
            this.ButtonZ = new System.Windows.Forms.Button();
            this.UpdateGUITimer = new System.Windows.Forms.Timer(this.components);
            this.LabelQ = new System.Windows.Forms.Label();
            this.LabelW = new System.Windows.Forms.Label();
            this.LabelE = new System.Windows.Forms.Label();
            this.LabelR = new System.Windows.Forms.Label();
            this.LabelT = new System.Windows.Forms.Label();
            this.LabelZ = new System.Windows.Forms.Label();
            this.LabelC = new System.Windows.Forms.Label();
            this.LabelX = new System.Windows.Forms.Label();
            this.LabelY = new System.Windows.Forms.Label();
            this.LabelP = new System.Windows.Forms.Label();
            this.LabelK = new System.Windows.Forms.Label();
            this.LabelJ = new System.Windows.Forms.Label();
            this.LabelH = new System.Windows.Forms.Label();
            this.LabelA = new System.Windows.Forms.Label();
            this.LabelO = new System.Windows.Forms.Label();
            this.LabelI = new System.Windows.Forms.Label();
            this.LabelU = new System.Windows.Forms.Label();
            this.LabelL = new System.Windows.Forms.Label();
            this.LabelN = new System.Windows.Forms.Label();
            this.LabelV = new System.Windows.Forms.Label();
            this.LabelG = new System.Windows.Forms.Label();
            this.LabelF = new System.Windows.Forms.Label();
            this.LabelD = new System.Windows.Forms.Label();
            this.LabelM = new System.Windows.Forms.Label();
            this.LabelB = new System.Windows.Forms.Label();
            this.LabelS = new System.Windows.Forms.Label();
            this.LabelRotorLeft = new System.Windows.Forms.Label();
            this.LabelRotorMid = new System.Windows.Forms.Label();
            this.LabelRotorRight = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.ButtonLeftDown = new System.Windows.Forms.Button();
            this.ButtonLeftUp = new System.Windows.Forms.Button();
            this.ButtonMidUp = new System.Windows.Forms.Button();
            this.ButtonRightUp = new System.Windows.Forms.Button();
            this.ButtonMidDown = new System.Windows.Forms.Button();
            this.ButtonRightDown = new System.Windows.Forms.Button();
            this.label1 = new System.Windows.Forms.Label();
            this.LabelPostInput = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.LabelPostLeft = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.LabelPostMid = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.LabelPostRight = new System.Windows.Forms.Label();
            this.LabelPreRight = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.LabelPreMid = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.LabelPreLeft = new System.Windows.Forms.Label();
            this.label21 = new System.Windows.Forms.Label();
            this.label22 = new System.Windows.Forms.Label();
            this.LabelPostReflector = new System.Windows.Forms.Label();
            this.label24 = new System.Windows.Forms.Label();
            this.LabelPreReflector = new System.Windows.Forms.Label();
            this.LabelPreOutput = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            this.ButtonQ.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonQ.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonQ.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonQ.Location = new System.Drawing.Point(207, 392);
            this.ButtonQ.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonQ.Name = "ButtonQ";
            this.ButtonQ.Size = new System.Drawing.Size(41, 38);
            this.ButtonQ.TabIndex = 0;
            this.ButtonQ.Text = "Q";
            this.ButtonQ.UseVisualStyleBackColor = true;
            this.ButtonQ.Click += new System.EventHandler(this.Button_Click);
            this.ButtonW.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonW.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonW.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonW.Location = new System.Drawing.Point(254, 392);
            this.ButtonW.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonW.Name = "ButtonW";
            this.ButtonW.Size = new System.Drawing.Size(41, 38);
            this.ButtonW.TabIndex = 1;
            this.ButtonW.Text = "W";
            this.ButtonW.UseVisualStyleBackColor = true;
            this.ButtonW.Click += new System.EventHandler(this.Button_Click);
            this.ButtonF.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonF.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonF.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonF.Location = new System.Drawing.Point(374, 435);
            this.ButtonF.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonF.Name = "ButtonF";
            this.ButtonF.Size = new System.Drawing.Size(41, 38);
            this.ButtonF.TabIndex = 2;
            this.ButtonF.Text = "F";
            this.ButtonF.UseVisualStyleBackColor = true;
            this.ButtonF.Click += new System.EventHandler(this.Button_Click);
            this.ButtonD.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonD.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonD.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonD.Location = new System.Drawing.Point(327, 435);
            this.ButtonD.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonD.Name = "ButtonD";
            this.ButtonD.Size = new System.Drawing.Size(41, 38);
            this.ButtonD.TabIndex = 3;
            this.ButtonD.Text = "D";
            this.ButtonD.UseVisualStyleBackColor = true;
            this.ButtonD.Click += new System.EventHandler(this.Button_Click);
            this.ButtonS.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonS.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonS.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonS.Location = new System.Drawing.Point(280, 435);
            this.ButtonS.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonS.Name = "ButtonS";
            this.ButtonS.Size = new System.Drawing.Size(41, 38);
            this.ButtonS.TabIndex = 4;
            this.ButtonS.Text = "S";
            this.ButtonS.UseVisualStyleBackColor = true;
            this.ButtonS.Click += new System.EventHandler(this.Button_Click);
            this.ButtonA.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonA.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonA.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonA.Location = new System.Drawing.Point(233, 435);
            this.ButtonA.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonA.Name = "ButtonA";
            this.ButtonA.Size = new System.Drawing.Size(41, 38);
            this.ButtonA.TabIndex = 5;
            this.ButtonA.Text = "A";
            this.ButtonA.UseVisualStyleBackColor = true;
            this.ButtonA.Click += new System.EventHandler(this.Button_Click);
            this.ButtonP.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonP.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonP.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonP.Location = new System.Drawing.Point(207, 478);
            this.ButtonP.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonP.Name = "ButtonP";
            this.ButtonP.Size = new System.Drawing.Size(41, 38);
            this.ButtonP.TabIndex = 6;
            this.ButtonP.Text = "P";
            this.ButtonP.UseVisualStyleBackColor = true;
            this.ButtonP.Click += new System.EventHandler(this.Button_Click);
            this.ButtonO.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonO.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonO.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonO.Location = new System.Drawing.Point(583, 392);
            this.ButtonO.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonO.Name = "ButtonO";
            this.ButtonO.Size = new System.Drawing.Size(41, 38);
            this.ButtonO.TabIndex = 7;
            this.ButtonO.Text = "O";
            this.ButtonO.UseVisualStyleBackColor = true;
            this.ButtonO.Click += new System.EventHandler(this.Button_Click);
            this.ButtonI.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonI.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonI.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonI.Location = new System.Drawing.Point(536, 392);
            this.ButtonI.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonI.Name = "ButtonI";
            this.ButtonI.Size = new System.Drawing.Size(41, 38);
            this.ButtonI.TabIndex = 8;
            this.ButtonI.Text = "I";
            this.ButtonI.UseVisualStyleBackColor = true;
            this.ButtonI.Click += new System.EventHandler(this.Button_Click);
            this.ButtonU.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonU.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonU.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonU.Location = new System.Drawing.Point(489, 392);
            this.ButtonU.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonU.Name = "ButtonU";
            this.ButtonU.Size = new System.Drawing.Size(41, 38);
            this.ButtonU.TabIndex = 9;
            this.ButtonU.Text = "U";
            this.ButtonU.UseVisualStyleBackColor = true;
            this.ButtonU.Click += new System.EventHandler(this.Button_Click);
            this.ButtonY.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonY.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonY.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonY.Location = new System.Drawing.Point(254, 478);
            this.ButtonY.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonY.Name = "ButtonY";
            this.ButtonY.Size = new System.Drawing.Size(41, 38);
            this.ButtonY.TabIndex = 10;
            this.ButtonY.Text = "Y";
            this.ButtonY.UseVisualStyleBackColor = true;
            this.ButtonY.Click += new System.EventHandler(this.Button_Click);
            this.ButtonT.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonT.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonT.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonT.Location = new System.Drawing.Point(395, 392);
            this.ButtonT.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonT.Name = "ButtonT";
            this.ButtonT.Size = new System.Drawing.Size(41, 38);
            this.ButtonT.TabIndex = 11;
            this.ButtonT.Text = "T";
            this.ButtonT.UseVisualStyleBackColor = true;
            this.ButtonT.Click += new System.EventHandler(this.Button_Click);
            this.ButtonR.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonR.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonR.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonR.Location = new System.Drawing.Point(348, 392);
            this.ButtonR.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonR.Name = "ButtonR";
            this.ButtonR.Size = new System.Drawing.Size(41, 38);
            this.ButtonR.TabIndex = 12;
            this.ButtonR.Text = "R";
            this.ButtonR.UseVisualStyleBackColor = true;
            this.ButtonR.Click += new System.EventHandler(this.Button_Click);
            this.ButtonE.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonE.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonE.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonE.Location = new System.Drawing.Point(301, 392);
            this.ButtonE.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonE.Name = "ButtonE";
            this.ButtonE.Size = new System.Drawing.Size(41, 38);
            this.ButtonE.TabIndex = 13;
            this.ButtonE.Text = "E";
            this.ButtonE.UseVisualStyleBackColor = true;
            this.ButtonE.Click += new System.EventHandler(this.Button_Click);
            this.ButtonL.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonL.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonL.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonL.Location = new System.Drawing.Point(583, 478);
            this.ButtonL.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonL.Name = "ButtonL";
            this.ButtonL.Size = new System.Drawing.Size(41, 38);
            this.ButtonL.TabIndex = 14;
            this.ButtonL.Text = "L";
            this.ButtonL.UseVisualStyleBackColor = true;
            this.ButtonL.Click += new System.EventHandler(this.Button_Click);
            this.ButtonK.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonK.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonK.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonK.Location = new System.Drawing.Point(562, 435);
            this.ButtonK.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonK.Name = "ButtonK";
            this.ButtonK.Size = new System.Drawing.Size(41, 38);
            this.ButtonK.TabIndex = 15;
            this.ButtonK.Text = "K";
            this.ButtonK.UseVisualStyleBackColor = true;
            this.ButtonK.Click += new System.EventHandler(this.Button_Click);
            this.ButtonJ.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonJ.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonJ.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonJ.Location = new System.Drawing.Point(515, 435);
            this.ButtonJ.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonJ.Name = "ButtonJ";
            this.ButtonJ.Size = new System.Drawing.Size(41, 38);
            this.ButtonJ.TabIndex = 16;
            this.ButtonJ.Text = "J";
            this.ButtonJ.UseVisualStyleBackColor = true;
            this.ButtonJ.Click += new System.EventHandler(this.Button_Click);
            this.ButtonH.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonH.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonH.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonH.Location = new System.Drawing.Point(468, 435);
            this.ButtonH.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonH.Name = "ButtonH";
            this.ButtonH.Size = new System.Drawing.Size(41, 38);
            this.ButtonH.TabIndex = 17;
            this.ButtonH.Text = "H";
            this.ButtonH.UseVisualStyleBackColor = true;
            this.ButtonH.Click += new System.EventHandler(this.Button_Click);
            this.ButtonG.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonG.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonG.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonG.Location = new System.Drawing.Point(421, 435);
            this.ButtonG.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonG.Name = "ButtonG";
            this.ButtonG.Size = new System.Drawing.Size(41, 38);
            this.ButtonG.TabIndex = 18;
            this.ButtonG.Text = "G";
            this.ButtonG.UseVisualStyleBackColor = true;
            this.ButtonG.Click += new System.EventHandler(this.Button_Click);
            this.ButtonM.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonM.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonM.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonM.Location = new System.Drawing.Point(536, 478);
            this.ButtonM.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonM.Name = "ButtonM";
            this.ButtonM.Size = new System.Drawing.Size(41, 38);
            this.ButtonM.TabIndex = 19;
            this.ButtonM.Text = "M";
            this.ButtonM.UseVisualStyleBackColor = true;
            this.ButtonM.Click += new System.EventHandler(this.Button_Click);
            this.ButtonN.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonN.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonN.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonN.Location = new System.Drawing.Point(489, 478);
            this.ButtonN.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonN.Name = "ButtonN";
            this.ButtonN.Size = new System.Drawing.Size(41, 38);
            this.ButtonN.TabIndex = 20;
            this.ButtonN.Text = "N";
            this.ButtonN.UseVisualStyleBackColor = true;
            this.ButtonN.Click += new System.EventHandler(this.Button_Click);
            this.ButtonB.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonB.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonB.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonB.Location = new System.Drawing.Point(442, 478);
            this.ButtonB.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonB.Name = "ButtonB";
            this.ButtonB.Size = new System.Drawing.Size(41, 38);
            this.ButtonB.TabIndex = 21;
            this.ButtonB.Text = "B";
            this.ButtonB.UseVisualStyleBackColor = true;
            this.ButtonB.Click += new System.EventHandler(this.Button_Click);
            this.ButtonV.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonV.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonV.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonV.Location = new System.Drawing.Point(395, 478);
            this.ButtonV.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonV.Name = "ButtonV";
            this.ButtonV.Size = new System.Drawing.Size(41, 38);
            this.ButtonV.TabIndex = 22;
            this.ButtonV.Text = "V";
            this.ButtonV.UseVisualStyleBackColor = true;
            this.ButtonV.Click += new System.EventHandler(this.Button_Click);
            this.ButtonC.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonC.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonC.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonC.Location = new System.Drawing.Point(348, 478);
            this.ButtonC.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonC.Name = "ButtonC";
            this.ButtonC.Size = new System.Drawing.Size(41, 38);
            this.ButtonC.TabIndex = 23;
            this.ButtonC.Text = "C";
            this.ButtonC.UseVisualStyleBackColor = true;
            this.ButtonC.Click += new System.EventHandler(this.Button_Click);
            this.ButtonX.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonX.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonX.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonX.Location = new System.Drawing.Point(301, 478);
            this.ButtonX.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonX.Name = "ButtonX";
            this.ButtonX.Size = new System.Drawing.Size(41, 38);
            this.ButtonX.TabIndex = 24;
            this.ButtonX.Text = "X";
            this.ButtonX.UseVisualStyleBackColor = true;
            this.ButtonX.Click += new System.EventHandler(this.Button_Click);
            this.ButtonZ.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonZ.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.ButtonZ.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (204)));
            this.ButtonZ.Location = new System.Drawing.Point(442, 392);
            this.ButtonZ.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonZ.Name = "ButtonZ";
            this.ButtonZ.Size = new System.Drawing.Size(41, 38);
            this.ButtonZ.TabIndex = 25;
            this.ButtonZ.Text = "Z";
            this.ButtonZ.UseVisualStyleBackColor = true;
            this.ButtonZ.Click += new System.EventHandler(this.Button_Click);
            this.UpdateGUITimer.Enabled = true;
            this.UpdateGUITimer.Tick += new System.EventHandler(this.TimerTick);
            this.LabelQ.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelQ.Location = new System.Drawing.Point(207, 242);
            this.LabelQ.Name = "LabelQ";
            this.LabelQ.Size = new System.Drawing.Size(41, 38);
            this.LabelQ.TabIndex = 26;
            this.LabelQ.Text = "Q";
            this.LabelQ.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelW.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelW.Location = new System.Drawing.Point(254, 242);
            this.LabelW.Name = "LabelW";
            this.LabelW.Size = new System.Drawing.Size(41, 38);
            this.LabelW.TabIndex = 27;
            this.LabelW.Text = "W";
            this.LabelW.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelE.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelE.Location = new System.Drawing.Point(301, 242);
            this.LabelE.Name = "LabelE";
            this.LabelE.Size = new System.Drawing.Size(41, 38);
            this.LabelE.TabIndex = 28;
            this.LabelE.Text = "E";
            this.LabelE.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelR.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelR.Location = new System.Drawing.Point(348, 242);
            this.LabelR.Name = "LabelR";
            this.LabelR.Size = new System.Drawing.Size(41, 38);
            this.LabelR.TabIndex = 29;
            this.LabelR.Text = "R";
            this.LabelR.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelT.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelT.Location = new System.Drawing.Point(395, 242);
            this.LabelT.Name = "LabelT";
            this.LabelT.Size = new System.Drawing.Size(41, 38);
            this.LabelT.TabIndex = 30;
            this.LabelT.Text = "T";
            this.LabelT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelZ.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelZ.Location = new System.Drawing.Point(442, 242);
            this.LabelZ.Name = "LabelZ";
            this.LabelZ.Size = new System.Drawing.Size(41, 38);
            this.LabelZ.TabIndex = 31;
            this.LabelZ.Text = "Z";
            this.LabelZ.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelC.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelC.Location = new System.Drawing.Point(348, 330);
            this.LabelC.Name = "LabelC";
            this.LabelC.Size = new System.Drawing.Size(41, 38);
            this.LabelC.TabIndex = 32;
            this.LabelC.Text = "C";
            this.LabelC.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelX.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelX.Location = new System.Drawing.Point(301, 330);
            this.LabelX.Name = "LabelX";
            this.LabelX.Size = new System.Drawing.Size(41, 38);
            this.LabelX.TabIndex = 33;
            this.LabelX.Text = "X";
            this.LabelX.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelY.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelY.Location = new System.Drawing.Point(254, 330);
            this.LabelY.Name = "LabelY";
            this.LabelY.Size = new System.Drawing.Size(41, 38);
            this.LabelY.TabIndex = 34;
            this.LabelY.Text = "Y";
            this.LabelY.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelP.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelP.Location = new System.Drawing.Point(207, 330);
            this.LabelP.Name = "LabelP";
            this.LabelP.Size = new System.Drawing.Size(41, 38);
            this.LabelP.TabIndex = 35;
            this.LabelP.Text = "P";
            this.LabelP.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelK.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelK.Location = new System.Drawing.Point(562, 286);
            this.LabelK.Name = "LabelK";
            this.LabelK.Size = new System.Drawing.Size(41, 38);
            this.LabelK.TabIndex = 36;
            this.LabelK.Text = "K";
            this.LabelK.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelJ.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelJ.Location = new System.Drawing.Point(515, 286);
            this.LabelJ.Name = "LabelJ";
            this.LabelJ.Size = new System.Drawing.Size(41, 38);
            this.LabelJ.TabIndex = 37;
            this.LabelJ.Text = "J";
            this.LabelJ.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelH.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelH.Location = new System.Drawing.Point(468, 286);
            this.LabelH.Name = "LabelH";
            this.LabelH.Size = new System.Drawing.Size(41, 38);
            this.LabelH.TabIndex = 38;
            this.LabelH.Text = "H";
            this.LabelH.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelA.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelA.Location = new System.Drawing.Point(233, 286);
            this.LabelA.Name = "LabelA";
            this.LabelA.Size = new System.Drawing.Size(41, 38);
            this.LabelA.TabIndex = 39;
            this.LabelA.Text = "A";
            this.LabelA.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelO.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelO.Location = new System.Drawing.Point(583, 242);
            this.LabelO.Name = "LabelO";
            this.LabelO.Size = new System.Drawing.Size(41, 38);
            this.LabelO.TabIndex = 40;
            this.LabelO.Text = "O";
            this.LabelO.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelI.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelI.Location = new System.Drawing.Point(536, 242);
            this.LabelI.Name = "LabelI";
            this.LabelI.Size = new System.Drawing.Size(41, 38);
            this.LabelI.TabIndex = 41;
            this.LabelI.Text = "I";
            this.LabelI.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelU.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelU.Location = new System.Drawing.Point(489, 242);
            this.LabelU.Name = "LabelU";
            this.LabelU.Size = new System.Drawing.Size(41, 38);
            this.LabelU.TabIndex = 42;
            this.LabelU.Text = "U";
            this.LabelU.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelL.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelL.Location = new System.Drawing.Point(583, 330);
            this.LabelL.Name = "LabelL";
            this.LabelL.Size = new System.Drawing.Size(41, 38);
            this.LabelL.TabIndex = 43;
            this.LabelL.Text = "L";
            this.LabelL.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelN.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelN.Location = new System.Drawing.Point(489, 330);
            this.LabelN.Name = "LabelN";
            this.LabelN.Size = new System.Drawing.Size(41, 38);
            this.LabelN.TabIndex = 44;
            this.LabelN.Text = "N";
            this.LabelN.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelV.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelV.Location = new System.Drawing.Point(395, 330);
            this.LabelV.Name = "LabelV";
            this.LabelV.Size = new System.Drawing.Size(41, 38);
            this.LabelV.TabIndex = 45;
            this.LabelV.Text = "V";
            this.LabelV.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelG.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelG.Location = new System.Drawing.Point(421, 286);
            this.LabelG.Name = "LabelG";
            this.LabelG.Size = new System.Drawing.Size(41, 38);
            this.LabelG.TabIndex = 46;
            this.LabelG.Text = "G";
            this.LabelG.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelF.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelF.Location = new System.Drawing.Point(374, 286);
            this.LabelF.Name = "LabelF";
            this.LabelF.Size = new System.Drawing.Size(41, 38);
            this.LabelF.TabIndex = 47;
            this.LabelF.Text = "F";
            this.LabelF.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelD.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelD.Location = new System.Drawing.Point(327, 286);
            this.LabelD.Name = "LabelD";
            this.LabelD.Size = new System.Drawing.Size(41, 38);
            this.LabelD.TabIndex = 48;
            this.LabelD.Text = "D";
            this.LabelD.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelM.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelM.Location = new System.Drawing.Point(536, 330);
            this.LabelM.Name = "LabelM";
            this.LabelM.Size = new System.Drawing.Size(41, 38);
            this.LabelM.TabIndex = 49;
            this.LabelM.Text = "M";
            this.LabelM.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelB.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelB.Location = new System.Drawing.Point(442, 330);
            this.LabelB.Name = "LabelB";
            this.LabelB.Size = new System.Drawing.Size(41, 38);
            this.LabelB.TabIndex = 50;
            this.LabelB.Text = "B";
            this.LabelB.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelS.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelS.Location = new System.Drawing.Point(280, 286);
            this.LabelS.Name = "LabelS";
            this.LabelS.Size = new System.Drawing.Size(41, 38);
            this.LabelS.TabIndex = 51;
            this.LabelS.Text = "S";
            this.LabelS.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelRotorLeft.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelRotorLeft.Location = new System.Drawing.Point(207, 71);
            this.LabelRotorLeft.Name = "LabelRotorLeft";
            this.LabelRotorLeft.Size = new System.Drawing.Size(41, 38);
            this.LabelRotorLeft.TabIndex = 52;
            this.LabelRotorLeft.Text = "A";
            this.LabelRotorLeft.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelRotorMid.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelRotorMid.Location = new System.Drawing.Point(327, 71);
            this.LabelRotorMid.Name = "LabelRotorMid";
            this.LabelRotorMid.Size = new System.Drawing.Size(41, 38);
            this.LabelRotorMid.TabIndex = 39;
            this.LabelRotorMid.Text = "A";
            this.LabelRotorMid.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelRotorRight.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.LabelRotorRight.Location = new System.Drawing.Point(453, 71);
            this.LabelRotorRight.Name = "LabelRotorRight";
            this.LabelRotorRight.Size = new System.Drawing.Size(41, 38);
            this.LabelRotorRight.TabIndex = 39;
            this.LabelRotorRight.Text = "A";
            this.LabelRotorRight.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.label4.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.label4.Location = new System.Drawing.Point(322, -144);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(41, 38);
            this.label4.TabIndex = 39;
            this.label4.Text = "A";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ButtonLeftDown.Location = new System.Drawing.Point(207, 112);
            this.ButtonLeftDown.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonLeftDown.Name = "ButtonLeftDown";
            this.ButtonLeftDown.Size = new System.Drawing.Size(41, 29);
            this.ButtonLeftDown.TabIndex = 53;
            this.ButtonLeftDown.Text = "v";
            this.ButtonLeftDown.UseVisualStyleBackColor = true;
            this.ButtonLeftDown.Click += new System.EventHandler(this.ButtonLeftDown_Click);
            this.ButtonLeftUp.Location = new System.Drawing.Point(207, 39);
            this.ButtonLeftUp.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonLeftUp.Name = "ButtonLeftUp";
            this.ButtonLeftUp.Size = new System.Drawing.Size(41, 29);
            this.ButtonLeftUp.TabIndex = 54;
            this.ButtonLeftUp.Text = "^";
            this.ButtonLeftUp.UseVisualStyleBackColor = true;
            this.ButtonLeftUp.Click += new System.EventHandler(this.ButtonLeftUp_Click);
            this.ButtonMidUp.Location = new System.Drawing.Point(327, 39);
            this.ButtonMidUp.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonMidUp.Name = "ButtonMidUp";
            this.ButtonMidUp.Size = new System.Drawing.Size(41, 29);
            this.ButtonMidUp.TabIndex = 54;
            this.ButtonMidUp.Text = "^";
            this.ButtonMidUp.UseVisualStyleBackColor = true;
            this.ButtonMidUp.Click += new System.EventHandler(this.ButtonMidUp_Click);
            this.ButtonRightUp.Location = new System.Drawing.Point(453, 39);
            this.ButtonRightUp.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonRightUp.Name = "ButtonRightUp";
            this.ButtonRightUp.Size = new System.Drawing.Size(41, 29);
            this.ButtonRightUp.TabIndex = 54;
            this.ButtonRightUp.Text = "^";
            this.ButtonRightUp.UseVisualStyleBackColor = true;
            this.ButtonRightUp.Click += new System.EventHandler(this.ButtonRightUp_Click);
            this.ButtonMidDown.Location = new System.Drawing.Point(327, 112);
            this.ButtonMidDown.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonMidDown.Name = "ButtonMidDown";
            this.ButtonMidDown.Size = new System.Drawing.Size(41, 29);
            this.ButtonMidDown.TabIndex = 53;
            this.ButtonMidDown.Text = "v";
            this.ButtonMidDown.UseVisualStyleBackColor = true;
            this.ButtonMidDown.Click += new System.EventHandler(this.ButtonMidDown_Click);
            this.ButtonRightDown.Location = new System.Drawing.Point(453, 112);
            this.ButtonRightDown.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ButtonRightDown.Name = "ButtonRightDown";
            this.ButtonRightDown.Size = new System.Drawing.Size(41, 29);
            this.ButtonRightDown.TabIndex = 53;
            this.ButtonRightDown.Text = "v";
            this.ButtonRightDown.UseVisualStyleBackColor = true;
            this.ButtonRightDown.Click += new System.EventHandler(this.ButtonRightDown_Click);
            this.label1.Location = new System.Drawing.Point(631, 444);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(26, 22);
            this.label1.TabIndex = 55;
            this.label1.Text = "->";
            this.LabelPostInput.Location = new System.Drawing.Point(663, 444);
            this.LabelPostInput.Name = "LabelPostInput";
            this.LabelPostInput.Size = new System.Drawing.Size(43, 22);
            this.LabelPostInput.TabIndex = 56;
            this.LabelPostInput.Text = "N/A";
            this.label3.Location = new System.Drawing.Point(248, 112);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(26, 22);
            this.label3.TabIndex = 55;
            this.label3.Text = "->";
            this.LabelPostLeft.Location = new System.Drawing.Point(280, 112);
            this.LabelPostLeft.Name = "LabelPostLeft";
            this.LabelPostLeft.Size = new System.Drawing.Size(43, 22);
            this.LabelPostLeft.TabIndex = 56;
            this.LabelPostLeft.Text = "N/A";
            this.label6.Location = new System.Drawing.Point(372, 112);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(26, 22);
            this.label6.TabIndex = 55;
            this.label6.Text = "->";
            this.LabelPostMid.Location = new System.Drawing.Point(404, 112);
            this.LabelPostMid.Name = "LabelPostMid";
            this.LabelPostMid.Size = new System.Drawing.Size(43, 22);
            this.LabelPostMid.TabIndex = 56;
            this.LabelPostMid.Text = "N/A";
            this.label8.Location = new System.Drawing.Point(493, 112);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(26, 22);
            this.label8.TabIndex = 55;
            this.label8.Text = "->";
            this.LabelPostRight.Location = new System.Drawing.Point(525, 112);
            this.LabelPostRight.Name = "LabelPostRight";
            this.LabelPostRight.Size = new System.Drawing.Size(43, 22);
            this.LabelPostRight.TabIndex = 56;
            this.LabelPostRight.Text = "N/A";
            this.LabelPreRight.Location = new System.Drawing.Point(525, 71);
            this.LabelPreRight.Name = "LabelPreRight";
            this.LabelPreRight.Size = new System.Drawing.Size(43, 22);
            this.LabelPreRight.TabIndex = 58;
            this.LabelPreRight.Text = "N/A";
            this.label11.Location = new System.Drawing.Point(493, 71);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(26, 22);
            this.label11.TabIndex = 57;
            this.label11.Text = "<-";
            this.label12.Location = new System.Drawing.Point(374, 71);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(26, 22);
            this.label12.TabIndex = 57;
            this.label12.Text = "<-";
            this.LabelPreMid.Location = new System.Drawing.Point(406, 71);
            this.LabelPreMid.Name = "LabelPreMid";
            this.LabelPreMid.Size = new System.Drawing.Size(43, 22);
            this.LabelPreMid.TabIndex = 58;
            this.LabelPreMid.Text = "N/A";
            this.label14.Location = new System.Drawing.Point(248, 71);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(26, 22);
            this.label14.TabIndex = 57;
            this.label14.Text = "<-";
            this.LabelPreLeft.Location = new System.Drawing.Point(280, 71);
            this.LabelPreLeft.Name = "LabelPreLeft";
            this.LabelPreLeft.Size = new System.Drawing.Size(43, 22);
            this.LabelPreLeft.TabIndex = 58;
            this.LabelPreLeft.Text = "N/A";
            this.label21.Location = new System.Drawing.Point(77, 9);
            this.label21.Name = "label21";
            this.label21.Size = new System.Drawing.Size(43, 191);
            this.label21.TabIndex = 60;
            this.label21.Text = "Р\r\nЕ\r\nФ\r\nЛ\r\nЕ\r\nК\r\nТ\r\nО\r\nР";
            this.label22.Location = new System.Drawing.Point(126, 112);
            this.label22.Name = "label22";
            this.label22.Size = new System.Drawing.Size(26, 22);
            this.label22.TabIndex = 55;
            this.label22.Text = "->";
            this.LabelPostReflector.Location = new System.Drawing.Point(158, 112);
            this.LabelPostReflector.Name = "LabelPostReflector";
            this.LabelPostReflector.Size = new System.Drawing.Size(43, 22);
            this.LabelPostReflector.TabIndex = 56;
            this.LabelPostReflector.Text = "N/A";
            this.label24.Location = new System.Drawing.Point(126, 71);
            this.label24.Name = "label24";
            this.label24.Size = new System.Drawing.Size(26, 22);
            this.label24.TabIndex = 57;
            this.label24.Text = "<-";
            this.LabelPreReflector.Location = new System.Drawing.Point(158, 71);
            this.LabelPreReflector.Name = "LabelPreReflector";
            this.LabelPreReflector.Size = new System.Drawing.Size(43, 22);
            this.LabelPreReflector.TabIndex = 58;
            this.LabelPreReflector.Text = "N/A";
            this.LabelPreOutput.Location = new System.Drawing.Point(663, 286);
            this.LabelPreOutput.Name = "LabelPreOutput";
            this.LabelPreOutput.Size = new System.Drawing.Size(43, 22);
            this.LabelPreOutput.TabIndex = 62;
            this.LabelPreOutput.Text = "N/A";
            this.label5.Location = new System.Drawing.Point(631, 286);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(26, 22);
            this.label5.TabIndex = 61;
            this.label5.Text = "<-";
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(833, 568);
            this.Controls.Add(this.LabelPreOutput);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label21);
            this.Controls.Add(this.LabelPreReflector);
            this.Controls.Add(this.LabelPreLeft);
            this.Controls.Add(this.LabelPreMid);
            this.Controls.Add(this.label24);
            this.Controls.Add(this.LabelPreRight);
            this.Controls.Add(this.label14);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.LabelPostRight);
            this.Controls.Add(this.LabelPostMid);
            this.Controls.Add(this.LabelPostReflector);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.LabelPostLeft);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label22);
            this.Controls.Add(this.LabelPostInput);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.ButtonRightUp);
            this.Controls.Add(this.ButtonMidUp);
            this.Controls.Add(this.ButtonLeftUp);
            this.Controls.Add(this.ButtonRightDown);
            this.Controls.Add(this.ButtonMidDown);
            this.Controls.Add(this.ButtonLeftDown);
            this.Controls.Add(this.LabelRotorLeft);
            this.Controls.Add(this.LabelS);
            this.Controls.Add(this.LabelB);
            this.Controls.Add(this.LabelM);
            this.Controls.Add(this.LabelD);
            this.Controls.Add(this.LabelF);
            this.Controls.Add(this.LabelG);
            this.Controls.Add(this.LabelV);
            this.Controls.Add(this.LabelN);
            this.Controls.Add(this.LabelL);
            this.Controls.Add(this.LabelU);
            this.Controls.Add(this.LabelI);
            this.Controls.Add(this.LabelO);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.LabelRotorRight);
            this.Controls.Add(this.LabelRotorMid);
            this.Controls.Add(this.LabelA);
            this.Controls.Add(this.LabelH);
            this.Controls.Add(this.LabelJ);
            this.Controls.Add(this.LabelK);
            this.Controls.Add(this.LabelP);
            this.Controls.Add(this.LabelY);
            this.Controls.Add(this.LabelX);
            this.Controls.Add(this.LabelC);
            this.Controls.Add(this.LabelZ);
            this.Controls.Add(this.LabelT);
            this.Controls.Add(this.LabelR);
            this.Controls.Add(this.LabelE);
            this.Controls.Add(this.LabelW);
            this.Controls.Add(this.LabelQ);
            this.Controls.Add(this.ButtonA);
            this.Controls.Add(this.ButtonB);
            this.Controls.Add(this.ButtonC);
            this.Controls.Add(this.ButtonD);
            this.Controls.Add(this.ButtonE);
            this.Controls.Add(this.ButtonF);
            this.Controls.Add(this.ButtonG);
            this.Controls.Add(this.ButtonH);
            this.Controls.Add(this.ButtonI);
            this.Controls.Add(this.ButtonJ);
            this.Controls.Add(this.ButtonK);
            this.Controls.Add(this.ButtonL);
            this.Controls.Add(this.ButtonM);
            this.Controls.Add(this.ButtonN);
            this.Controls.Add(this.ButtonO);
            this.Controls.Add(this.ButtonP);
            this.Controls.Add(this.ButtonQ);
            this.Controls.Add(this.ButtonR);
            this.Controls.Add(this.ButtonS);
            this.Controls.Add(this.ButtonT);
            this.Controls.Add(this.ButtonU);
            this.Controls.Add(this.ButtonV);
            this.Controls.Add(this.ButtonW);
            this.Controls.Add(this.ButtonX);
            this.Controls.Add(this.ButtonY);
            this.Controls.Add(this.ButtonZ);
            this.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.Name = "Form1";
            this.Text = "EnigmaSim - Enigma I (Service)";
            this.ResumeLayout(false);
        }

        #region Windows Form Designer generated code

        #endregion

        private System.Windows.Forms.Button ButtonQ;
        private System.Windows.Forms.Button ButtonZ;
        private System.Windows.Forms.Button ButtonX;
        private System.Windows.Forms.Button ButtonC;
        private System.Windows.Forms.Button ButtonV;
        private System.Windows.Forms.Button ButtonB;
        private System.Windows.Forms.Button ButtonN;
        private System.Windows.Forms.Button ButtonM;
        private System.Windows.Forms.Button ButtonG;
        private System.Windows.Forms.Button ButtonH;
        private System.Windows.Forms.Button ButtonJ;
        private System.Windows.Forms.Button ButtonK;
        private System.Windows.Forms.Button ButtonL;
        private System.Windows.Forms.Button ButtonE;
        private System.Windows.Forms.Button ButtonR;
        private System.Windows.Forms.Button ButtonT;
        private System.Windows.Forms.Button ButtonY;
        private System.Windows.Forms.Button ButtonU;
        private System.Windows.Forms.Button ButtonI;
        private System.Windows.Forms.Button ButtonO;
        private System.Windows.Forms.Button ButtonP;
        private System.Windows.Forms.Button ButtonA;
        private System.Windows.Forms.Button ButtonS;
        private System.Windows.Forms.Button ButtonD;
        private System.Windows.Forms.Button ButtonF;
        private System.Windows.Forms.Button ButtonW;
        private System.Windows.Forms.Timer UpdateGUITimer;
        private System.Windows.Forms.Label LabelQ;
        private System.Windows.Forms.Label LabelB;
        private System.Windows.Forms.Label LabelM;
        private System.Windows.Forms.Label LabelD;
        private System.Windows.Forms.Label LabelF;
        private System.Windows.Forms.Label LabelV;
        private System.Windows.Forms.Label LabelN;
        private System.Windows.Forms.Label LabelL;
        private System.Windows.Forms.Label LabelU;
        private System.Windows.Forms.Label LabelI;
        private System.Windows.Forms.Label LabelO;
        private System.Windows.Forms.Label LabelA;
        private System.Windows.Forms.Label LabelH;
        private System.Windows.Forms.Label LabelJ;
        private System.Windows.Forms.Label LabelK;
        private System.Windows.Forms.Label LabelP;
        private System.Windows.Forms.Label LabelY;
        private System.Windows.Forms.Label LabelX;
        private System.Windows.Forms.Label LabelC;
        private System.Windows.Forms.Label LabelZ;
        private System.Windows.Forms.Label LabelT;
        private System.Windows.Forms.Label LabelR;
        private System.Windows.Forms.Label LabelE;
        private System.Windows.Forms.Label LabelW;
        private System.Windows.Forms.Label LabelG;
        private System.Windows.Forms.Label LabelS;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label LabelRotorLeft;
        private System.Windows.Forms.Label LabelRotorMid;
        private System.Windows.Forms.Label LabelRotorRight;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label21;
        private System.Windows.Forms.Label label24;
        private System.Windows.Forms.Label label22;
        private System.Windows.Forms.Label LabelPreOutput;
        private System.Windows.Forms.Label LabelPostReflector;
        private System.Windows.Forms.Label LabelPreReflector;
        private System.Windows.Forms.Label LabelPreMid;
        private System.Windows.Forms.Label LabelPreLeft;
        private System.Windows.Forms.Label LabelPostRight;
        private System.Windows.Forms.Label LabelPreRight;
        private System.Windows.Forms.Label LabelPostLeft;
        private System.Windows.Forms.Label LabelPostMid;
        private System.Windows.Forms.Label LabelPostInput;
        private System.Windows.Forms.Button ButtonMidDown;
        private System.Windows.Forms.Button ButtonRightDown;
        private System.Windows.Forms.Button ButtonLeftDown;
        private System.Windows.Forms.Button ButtonLeftUp;
        private System.Windows.Forms.Button ButtonMidUp;
        private System.Windows.Forms.Button ButtonRightUp;
    }
}